name: Build and Test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env: 
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: Hurtownia-Database
        ports:
          - 5432:5432
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn -f pom.xml clean install -B

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      
      - name: Setup env variables
        env:
          DB_PORT: 5432
          HOST_NAME: db
          DB_NAME: Hurtownia-Database
          DB_USERNAME: postgres
          DB_PASSWORD: admin
        
      - name: Run tests
        run: mvn -f backend/pom.xml test
